php artisan make:model StatesModel
php artisan make:model DistrictModel
php artisan make:model SubdistrictModel
php artisan make:model FeesHeadModel
php artisan make:model AcademicYearModel
php artisan make:model CategoriesModel
php artisan make:model ClassesModel
php artisan make:model FeesDetailsModel
php artisan make:model CasteModel
php artisan make:model AdmissionModel